server:
  port: 8770
spring:
  application:
    name: goods
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 49.232.135.209:9300
  elasticsearch:
    rest:
      uris: ["http://49.232.135.209:9200"]
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

feign:
  hystrix:
    enabled: true
#开启hystrix stream监控
management:
  endpoints:
    web:
      exposure:
        include: '*'

#turbine:
#  appConfig: 'hystrix-feign-demo'
#  turbine:
#    aggregator:
#      clusterConfig: default
#    clusterNameExpression: new String("default")
