spring:
  datasource:
    url: jdbc:mysql://49.232.135.209:3306/permission
    username: root
    password: wmzh123@qwe
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
#    password: 123456
    port: 6379
server:
  port: 8080